package application.classiGeneriche;

public enum RiskFactor {
    FUMATORE, EX_FUMATORE, OBESITA, DIPENDENZA_ALCOOL, EX_DIPENDENZA_ALCOOL, DIPENDENZA_STUPEFACENTI, EX_DIPENDENZA_STUPEFACENTI, ALTRA_DIPENDENZA
}
